"$schema" = 'https://starship.rs/config-schema.json'

format = """
$time\
$directory\
$git_branch$git_status\
$c$cpp$rust$golang$nodejs$java$kotlin$python\
$cmd_duration\
$line_break$character"""

[time]
disabled = false
time_format = "%T"
format = '\[[$time]($style)\] '

[directory]
read_only = " 󰌾"
truncation_length = 6
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
symbol = ""
format = '[$symbol $branch(:$remote_branch)]($style) '

[c]
format = '[$symbol($version)]($style) '

[cpp]
format = '[$symbol($version)]($style) '

[rust]
format = '[$symbol($version)]($style) '

[golang]
format = '[$symbol($version)]($style) '

[nodejs]
format = '[$symbol($version)]($style) '

[java]
format = '[$symbol($version)]($style) '

[kotlin]
format = '[$symbol($version)]($style) '

[python]
format = '[$symbol($version)]($style) '

[cmd_duration]
min_time = 2000
format = '[ $duration]($style) '

[line_break]
disabled = false
